services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DOCKER_PG_USER}
      POSTGRES_PASSWORD: ${DOCKER_PG_PASSWORD}
      POSTGRES_DB: ${DOCKER_PG_DBNAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DOCKER_PG_USER} -d ${DOCKER_PG_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      SMTP_USER: ${DOCKER_SMTP_USER}
      SMTP_PASS: ${DOCKER_SMTP_PASS}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:

