CREATE TABLE settings (
    id SERIAL PRIMARY KEY,
    param VARCHAR(255) UNIQUE NOT NULL,
    value VARCHAR(255) NOT NULL,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);
